set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports data_valid]
set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN T18 [get_ports tx_start]
set_property IOSTANDARD LVCMOS33 [get_ports tx_start]
set_property PACKAGE_PIN P1 [get_ports data_valid]
set_property PACKAGE_PIN L1 [get_ports tx_done_tick]
set_property IOSTANDARD LVCMOS33 [get_ports tx_done_tick]
set_property PACKAGE_PIN V17 [get_ports {tx_din[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_din[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_din[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_din[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_din[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_din[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_din[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_din[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_din[0]}]
set_property PACKAGE_PIN V16 [get_ports {tx_din[6]}]
set_property PACKAGE_PIN W16 [get_ports {tx_din[5]}]
set_property PACKAGE_PIN W17 [get_ports {tx_din[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[0]}]
set_property PACKAGE_PIN U16 [get_ports {data_out[7]}]
set_property PACKAGE_PIN E19 [get_ports {data_out[6]}]
set_property PACKAGE_PIN U19 [get_ports {data_out[5]}]
set_property PACKAGE_PIN V19 [get_ports {data_out[4]}]
set_property PACKAGE_PIN W18 [get_ports {data_out[3]}]
set_property PACKAGE_PIN U15 [get_ports {data_out[2]}]
set_property PACKAGE_PIN U14 [get_ports {data_out[1]}]
set_property PACKAGE_PIN V14 [get_ports {data_out[0]}]

set_property PACKAGE_PIN W15 [get_ports {tx_din[3]}]
set_property PACKAGE_PIN V15 [get_ports {tx_din[2]}]
set_property PACKAGE_PIN W14 [get_ports {tx_din[1]}]
set_property PACKAGE_PIN W13 [get_ports {tx_din[0]}]

set_property PACKAGE_PIN B18 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN A18 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]